# SMS-Activate / HeroSMS 服务名称映射表
SERVICE_NAMES = {
        # ─── 常用服务 ───
        'ot': 'OpenAI / Telegram (通用)', 'tg': 'Telegram', 'wa': 'WhatsApp',
        'go': 'Google / Gmail', 'fb': 'Facebook', 'tw': 'Twitter / X',
        'ig': 'Instagram', 'li': 'LinkedIn', 'dc': 'Discord', 'ti': 'Tinder',
        'am': 'Amazon', 'ub': 'Uber', 'av': 'Avito', 'ok': 'Odnoklassniki',
        'vk': 'VKontakte', 'mb': 'Mail.ru', 'me': 'WeChat / 微信',
        'sn': 'Snapchat', 'pi': 'Pinterest', 'tb': 'TikTok',
        'zz': 'Zoom', 'mm': 'Microsoft / Outlook', 'al': 'Alibaba',
        'ks': 'Kuaishou / 快手', 'jd': 'JD / 京东', 'ad': 'Apple ID',
        'bt': 'Bittrex', 'cb': 'Coinbase', 'bn': 'Binance',
        'hl': 'Huobi', 'okx': 'OKX', 'kf': 'KuCoin',
        'gv': 'Google Voice', 'nt': 'Netflix', 'sp': 'Spotify',
        'ym': 'Yandex', 'yu': 'Yahoo', 'mi': 'Microsoft (OLD)',
        'wk': 'Weibo / 微博', 'db': 'DiDi / 滴滴', 'mt': 'Meituan / 美团',
        'pd': 'Pinduoduo / 拼多多', 'wb': 'Weibo Business',
        'wp': 'WhatsApp Business', 'vp': 'Viber', 'wf': 'Wire',
        'ac': 'Airbnb', 'ae': 'Ae (应用)', 'ag': 'Agora',
        'ap': 'Apple (其他)', 'as': 'Asobu', 'az': 'Aliexpress',
        'ba': 'Badoo', 'bb': 'Bigo Live', 'bc': 'Bing / Clarity',
        'be': 'Bumble', 'bf': 'Bank of...', 'bg': 'BongaCams',
        'bk': 'Booking', 'bn': 'Binance', 'bo': 'Bonga Cams',
        'bq': 'BitMEX', 'br': 'Bumble', 'bt': 'Bittrex',
        'by': 'Bybit', 'ca': 'Cash App', 'cc': 'CoinMarketCap',
        'cd': 'Crypto.com', 'ce': 'CoinEx', 'cf': 'Cloudflare',
        'cg': 'CoinGate', 'ch': 'Chatous', 'cl': 'CoinList',
        'co': 'Coinsbit', 'cr': 'CrickWatch', 'ct': 'CoinTracker',
        'dc': 'Discord', 'dg': 'DingTalk / 钉钉', 'di': 'DingTalk',
        'dj': 'DJI / 大疆', 'dk': 'Docker', 'dl': 'Dlive',
        'dm': 'DMarket', 'do': 'DoorDash', 'dp': 'Did (Passenger)',
        'dr': 'DoorDash', 'ds': 'DingTalk (服务)', 'dt': 'DiDi (Driver)',
        'du': 'DuckDuckGo', 'ea': 'EA / Origin', 'eb': 'eBay',
        'ee': 'Evernote', 'ei': 'Etsy', 'em': 'Email (通用)',
        'et': 'Ethereum', 'ev': 'Eventbrite', 'ex': 'Exchange',
        'fc': 'FaceCall', 'fd': 'Foodpanda', 'fi': 'Fiverr',
        'fl': 'Flickr', 'fp': 'Facebook Pay', 'fr': 'Freelancer',
        'ft': 'FTMO', 'ga': 'Game (通用)', 'gb': 'Grab',
        'gc': 'GCash', 'gd': 'GoDaddy', 'ge': 'Get Taxi',
        'gf': 'GoFundMe', 'gh': 'GitHub', 'gi': 'Gittigidiyor',
        'gl': 'Glovo', 'gm': 'Gmail', 'gn': 'Genesis',
        'gp': 'Google Pay', 'gr': 'Grindr', 'gs': 'Google Play Store',
        'gt': 'Gett', 'gu': 'Guru', 'gw': 'Google Workspace',
        'hb': 'HBase', 'hk': 'Huawei / 华为', 'hl': 'Huobi',
        'hn': 'Huawei (NEW)', 'hp': 'Huawei Pay', 'hr': 'Huawei (ROM)',
        'hs': 'Huawei Store', 'ht': 'Huawei (Ticket)', 'hu': 'Huawei',
        'ic': 'ICQ', 'in': 'Indeed', 'it': 'Itch.io',
        'jd': 'JD / 京东', 'jo': 'Joom', 'jp': 'JPay',
        'ka': 'Kaggle', 'kb': 'K-Bank', 'kc': 'KC',
        'ki': 'Kick', 'kl': 'KL', 'ko': 'Koho',
        'kr': 'Kraken', 'ks': 'Kuaishou / 快手', 'kt': 'KT',
        'la': 'Lazada', 'lb': 'LBank', 'le': 'Line',
        'lg': 'LG', 'lk': 'LK', 'ln': 'LN',
        'lo': 'LO', 'lp': 'LP', 'lr': 'LR',
        'ls': 'LS', 'lt': 'LT', 'lu': 'Lunch',
        'ly': 'LY', 'mb': 'Mail.ru', 'me': 'WeChat / 微信',
        'mf': 'MF', 'mg': 'MG', 'mh': 'MH',
        'mi': 'Microsoft (OLD)', 'mj': 'MJ', 'mk': 'MK',
        'ml': 'ML', 'mm': 'Microsoft / Outlook', 'mn': 'MN',
        'mo': 'Moco', 'mp': 'MP', 'mq': 'MQ',
        'mr': 'Mercado / MercadoLibre', 'ms': 'MS', 'mt': 'Meituan / 美团',
        'mu': 'MU', 'mv': 'MV', 'mw': 'MW',
        'mx': 'Mx', 'my': 'MY', 'mz': 'MZ',
        'na': 'Naver', 'nb': 'NB', 'nc': 'NC',
        'nd': 'ND', 'ne': 'NE', 'nf': 'Netflix',
        'ng': 'NG', 'nh': 'NH', 'ni': 'Nike',
        'nj': 'NJ', 'nk': 'NK', 'nl': 'NL',
        'nm': 'NM', 'nn': 'NN', 'no': 'NO',
        'np': 'NP', 'nq': 'NQ', 'nr': 'NR',
        'ns': 'NS', 'nt': 'Netflix', 'nu': 'NU',
        'nv': 'NV', 'nw': 'NW', 'nx': 'NX',
        'ny': 'NY', 'nz': 'NZ', 'ob': 'OB',
        'oc': 'OC', 'od': 'OD', 'oe': 'OE',
        'of': 'OF', 'og': 'OG', 'oh': 'OH',
        'oi': 'OI', 'oj': 'OJ', 'ok': 'Odnoklassniki',
        'okx': 'OKX', 'ol': 'OL', 'om': 'OM',
        'on': 'ON', 'oo': 'OO', 'op': 'OP',
        'oq': 'OQ', 'or': 'OR', 'os': 'OS',
        'ot': 'OpenAI / Telegram (通用)', 'ou': 'OU', 'ov': 'OV',
        'ow': 'OW', 'ox': 'OX', 'oy': 'OY',
        'oz': 'OZ', 'pa': 'PA', 'pb': 'PB',
        'pc': 'PC', 'pd': 'Pinduoduo / 拼多多', 'pe': 'PE',
        'pf': 'PF', 'pg': 'PG', 'ph': 'PH',
        'pi': 'Pinterest', 'pj': 'PJ', 'pk': 'PK',
        'pl': 'PL', 'pm': 'PM', 'pn': 'PN',
        'po': 'PO', 'pp': 'PP', 'pq': 'PQ',
        'pr': 'PR', 'ps': 'PS', 'pt': 'PT',
        'pu': 'PU', 'pv': 'PV', 'pw': 'PW',
        'px': 'PX', 'py': 'PY', 'pz': 'PZ',
        'qa': 'QA', 'qb': 'QB', 'qc': 'QC',
        'qd': 'QD', 'qe': 'QE', 'qf': 'QF',
        'qg': 'QG', 'qh': 'QH', 'qi': 'QI',
        'qj': 'QJ', 'qk': 'QK', 'ql': 'QL',
        'qm': 'QM', 'qn': 'QN', 'qo': 'QO',
        'qp': 'QP', 'qq': 'QQ', 'qr': 'QR',
        'qs': 'QS', 'qt': 'QT', 'qu': 'QU',
        'qv': 'QV', 'qw': 'QW', 'qx': 'QX',
        'qy': 'QY', 'qz': 'QZ', 'ra': 'RA',
        'rb': 'RB', 'rc': 'RC', 'rd': 'RD',
        're': 'RE', 'rf': 'RF', 'rg': 'RG',
        'rh': 'RH', 'ri': 'RI', 'rj': 'RJ',
        'rk': 'RK', 'rl': 'RL', 'rm': 'RM',
        'rn': 'RN', 'ro': 'RO', 'rp': 'RP',
        'rq': 'RQ', 'rr': 'RR', 'rs': 'RS',
        'rt': 'RT', 'ru': 'RU', 'rv': 'RV',
        'rw': 'RW', 'rx': 'RX', 'ry': 'RY',
        'rz': 'RZ', 'sa': 'SA', 'sb': 'SB',
        'sc': 'SC', 'sd': 'SD', 'se': 'SE',
        'sf': 'SF', 'sg': 'SG', 'sh': 'SH',
        'si': 'SI', 'sj': 'SJ', 'sk': 'SK',
        'sl': 'SL', 'sm': 'SM', 'sn': 'Snapchat',
        'so': 'SO', 'sp': 'Spotify', 'sq': 'SQ',
        'sr': 'SR', 'ss': 'SS', 'st': 'ST',
        'su': 'SU', 'sv': 'SV', 'sw': 'SW',
        'sx': 'SX', 'sy': 'SY', 'sz': 'SZ',
        'ta': 'TA', 'tb': 'TikTok', 'tc': 'TC',
        'td': 'TD', 'te': 'TE', 'tf': 'TF',
        'tg': 'Telegram', 'th': 'TH', 'ti': 'Tinder',
        'tj': 'TJ', 'tk': 'TK', 'tl': 'TL',
        'tm': 'TM', 'tn': 'TN', 'to': 'TO',
        'tp': 'TP', 'tq': 'TQ', 'tr': 'TR',
        'ts': 'TS', 'tt': 'TT', 'tu': 'TU',
        'tv': 'TV', 'tw': 'Twitter / X', 'tx': 'TX',
        'ty': 'TY', 'tz': 'TZ', 'ua': 'UA',
        'ub': 'Uber', 'uc': 'UC', 'ud': 'UD',
        'ue': 'UE', 'uf': 'UF', 'ug': 'UG',
        'uh': 'UH', 'ui': 'UI', 'uj': 'UJ',
        'uk': 'UK', 'ul': 'Ukrnet', 'um': 'UM',
        'un': 'UN', 'uo': 'UO', 'up': 'UP',
        'uq': 'UQ', 'ur': 'UR', 'us': 'US',
        'ut': 'UT', 'uu': 'UU', 'uv': 'UV',
        'uw': 'UW', 'ux': 'UX', 'uy': 'UY',
        'uz': 'UZ', 'va': 'VA', 'vb': 'VB',
        'vc': 'VC', 'vd': 'VD', 've': 'VE',
        'vf': 'VF', 'vg': 'VG', 'vh': 'VH',
        'vi': 'VI', 'vj': 'VJ', 'vk': 'VKontakte',
        'vl': 'VL', 'vm': 'VM', 'vn': 'VN',
        'vo': 'VO', 'vp': 'Viber', 'vq': 'VQ',
        'vr': 'VR', 'vs': 'VS', 'vt': 'VT',
        'vu': 'VU', 'vv': 'VV', 'vw': 'VW',
        'vx': 'VX', 'vy': 'VY', 'vz': 'VZ',
        'wa': 'WhatsApp', 'wb': 'Weibo / 微博 (Business)',
        'wc': 'WC', 'wd': 'WD', 'we': 'WE',
        'wf': 'Wire', 'wg': 'WG', 'wh': 'WH',
        'wi': 'WI', 'wj': 'WJ', 'wk': 'Weibo / 微博',
        'wl': 'WL', 'wm': 'WM', 'wn': 'WN',
        'wo': 'WO', 'wp': 'WhatsApp Business', 'wq': 'WQ',
        'wr': 'WR', 'ws': 'WS', 'wt': 'WT',
        'wu': 'WU', 'wv': 'WV', 'ww': 'WW',
        'wx': 'WX', 'wy': 'WY', 'wz': 'WZ',
        'xa': 'XA', 'xb': 'XB', 'xc': 'XC',
        'xd': 'XD', 'xe': 'XE', 'xf': 'XF',
        'xg': 'XG', 'xh': 'XH', 'xi': 'XI',
        'xj': 'XJ', 'xk': 'XK', 'xl': 'XL',
        'xm': 'XM', 'xn': 'XN', 'xo': 'XO',
        'xp': 'XP', 'xq': 'XQ', 'xr': 'XR',
        'xs': 'XS', 'xt': 'XT', 'xu': 'XU',
        'xv': 'XV', 'xw': 'XW', 'xx': 'XX',
        'xy': 'XY', 'xz': 'XZ', 'ya': 'YA',
        'yb': 'YB', 'yc': 'Yandex Cloud', 'yd': 'YD',
        'ye': 'YE', 'yf': 'YF', 'yg': 'YG',
        'yh': 'YH', 'yi': 'YI', 'yj': 'YJ',
        'yk': 'YK', 'yl': 'YL', 'ym': 'Yandex',
        'yn': 'Yandex (NEW)', 'yo': 'YO', 'yp': 'YP',
        'yq': 'YQ', 'yr': 'YR', 'ys': 'YS',
        'yt': 'YT', 'yu': 'Yahoo', 'yv': 'YV',
        'yw': 'YW', 'yx': 'YX', 'yy': 'YY',
        'yz': 'YZ', 'za': 'ZA', 'zb': 'ZB',
        'zc': 'ZC', 'zd': 'ZD', 'ze': 'ZE',
        'zf': 'ZF', 'zg': 'ZG', 'zh': 'ZH',
        'zi': 'ZI', 'zj': 'ZJ', 'zk': 'ZK',
        'zl': 'ZL', 'zm': 'ZM', 'zn': 'ZN',
        'zo': 'ZO', 'zp': 'ZP', 'zq': 'ZQ',
        'zr': 'ZR', 'zs': 'ZS', 'zt': 'ZT',
        'zu': 'ZU', 'zv': 'ZV', 'zw': 'ZW',
        'zx': 'ZX', 'zy': 'ZY', 'zz': 'Zoom',
        # ─── 特殊 ───
        'aw': 'Any Other / 其他服务',
        'an': 'Any Other (NEW)',
    }
